language: node_js
node_js:
- 8
- 10
install:
- npm install
script:
- npm run lint
- npm test
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
